### PR TITLE
Scraper maintenance

### PR DESCRIPTION
**Pull request by divergentdave**
Various changes to fix broken scrapers
- [x] gpo
- [x] peacecorps
- [x] commerce
- [x] ncua
- [x] pbgc
- [x] opm
- [x] exim
- [x] arc
- [x] cncs
- [x] hud

### CODE REVIEW

**Comment by divergentdave** [comment]
Argh, this page on the HUD OIG archives no longer has links.
http://archives.hud.gov/offices/oig/reports/de.cfm
https://web.archive.org/web/20130218181056/http://archives.hud.gov/offices/oig/reports/de.cfm

**Comment by divergentdave** [comment]
Ah, it looks like these links were always broken. We have them in BAD_LINKS. I'll fix the scraper to parse the rest of the page.

**Comment by konklone** [comment]
Sounds good, I'll await a fix for HUD -- but thank you for these fixes! They seemed to grow pretty quickly.

**Comment by divergentdave** [comment]
Ready to go!

**Comment by konklone** [comment]
Very, very nice job. These take more hand-holding than I expected. Thank you!

**Pull request merged**
