### PR TITLE
More unique report_id fixes

### LINKED ISSUE #197: Dupe report IDs in 2014 and 2015
From a 2014+2015 re-archive, HHS reports these:

```
[hhs] Duplicate report_id: 61200041 has been used twice this session
[hhs] Duplicate report_id: 21102017 has been used twice this session
[hhs] Duplicate report_id: 21202013 has been used twice this session
[hhs] Duplicate report_id: 21101039 has been used twice this session
[hhs] Duplicate report_id: 91201001 has been used twice this session
[hhs] Duplicate report_id: 41201016 has been used twice this session
[hhs] Duplicate report_id: oei-09-11-00380 has been used twice this session
```

There are a few dupes in other scrapers:

```
[arc] Duplicate report_id: report14-21-sc-17044 has been used twice this session
[energy] Duplicate report_id: DOE-IG-0919 is saved under 2015 and 2014
[pbgc] Duplicate report_id: - has been used twice this session
[pbgc] Duplicate report_id: - has been used twice this session
[usps] Duplicate report_id: rarc-wp-14-014 has been used twice this session
```

The `pbgc` scraper shouldn't use `-` as an ID. I think that merits an update to the validation check, maybe that at least one alphanumeric character be present.

### PR DESCRIPTION
**Pull request by divergentdave**
WIP, this will fix #197 and more.

- [x] agriculture
- [x] arc
- [x] dod
- [x] hhs
- [x] pbgc
- [x] sba
- [x] treasury
- [x] usps

### CODE REVIEW

**Comment by divergentdave** [comment]
The dupe from the ARC scraper is a copy-paste error in the website. I've emailed the webmaster.

**Comment by divergentdave** [comment]
I've been looking into the USPS scraper, and it seems that the USPS document library is nondeterministic. If you download one page over and over like so...

```
curl 'https://uspsoig.gov/document-library?type=All&field_doc_date_value%5Bvalue%5D=1998-01-01&field_doc_cat_tid%5B1920%5D=1920&field_doc_cat_tid%5B1923%5D=1923&field_doc_cat_tid%5B1922%5D=1922&page=0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C6' > 6a.html
```

... you will find that reports issued on the same day show up in a different order between different page loads. This causes warnings for us when, for example, a report appears at the end of page 6 and also the beginning of page 7 when we grab it. Of course, if that happens, it means we're also missing a report at the same page boundary. I'll deal with doubling up on reports now, and open up an issue for later to investigate automatically retrying pages when we miss something.

**Comment by divergentdave** [comment]
It's done, ready for review!

**Comment by konklone** [comment]
This is outstanding, comprehensive work, @divergentdave. Thank you for doing this. Integrating into the production servers now.

**Pull request merged**
